spring.datasource.url=jdbc:postgresql://localhost:5433/budget_db
spring.datasource.username=postgres
spring.datasource.password=ton_mot_de_passe

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Debug SQL (optionnel)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8082